### ISSUE TITLE
Compatibility with Welcome robot extension

### ISSUE THREAD

**Issue by Galixte** [kinerity/topicdescriptions#2]
Hi @kinerity,

with the extension Welcome Robot: https://github.com/alifaraji/welcomerobot/.

There is an error when a user logs for fisrt time, after his registration.

Could you fix it please ?

Regards.

**Comment by kinerity** [comment]
As with the quickedit extension, this is not something I can fix. Extensions that modify or create posts need to check if this extension is installed and act appropriately. Please report those issues to the extension author.

**Comment by Galixte** [comment]
Please Kinerty, could you submit a fix to take in consideration your TOPIC_DESC field for this extension ?

The author of this extension @alifaraji, doesn’t answer to my requests since a few months.

**Comment by Galixte** [comment]
I think it’s below the lines: https://github.com/alifaraji/welcomerobot/blob/master/event/listener.php#L117, that we have to add your topic_desc field.

**Comment by kinerity** [comment]
You should be able to do something similar to what mark did for the quickedit extension.

**Comment by Galixte** [comment]
I’m not coder, i don’t know PHP code, you are the one which will become my hero if you could take a look, please.

**Comment by kinerity** [comment]
Try adding `'topic_desc' => '',` to the $data array.

**Comment by Galixte** [comment]
Many thanks ! It’s work like a charm.
